spring:
  config:
    import:
      - classpath:secret/prod-db.yml
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
